kind: pipeline
name: integration

steps:
    - name: nextcloud
      image: nextcloudci/php8.0:latest
      environment:
          APP_NAME: officeonline
          CORE_BRANCH: master
          DB: sqlite
      commands:
          - bash ./tests/drone-server-setup.sh $APP_NAME $CORE_BRANCH $DB
          - cd ../server
          - ./occ app:enable $APP_NAME
          - ./occ config:system:set allow_local_remote_servers --value true --type bool
          - cd apps/$APP_NAME

          # Run integration tests
          - cd tests
          - bash run-integration.sh features/wopi
services:
    - name: collabora
      image: collabora/code:latest
      environment:
          extra_params: '--o:ssl.enable=false'
          domain: 'nextcloud'

trigger:
    branch:
        - master
        - stable*
    event:
        - pull_request
        - push
